<a href="https://colab.research.google.com/github/hkwu6013/Git-ting-started/blob/master/%E2%80%9Ctensor_tutorial_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[2.8409e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [2.5668e-09, 2.1083e-07, 1.0812e-05],
        [4.2281e+21, 3.3797e+21, 1.0692e-05],
        [8.4951e+20, 1.3162e+22, 5.0948e-14]])


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3915, 0.9309, 0.1498],
        [0.3022, 0.4960, 0.2657],
        [0.0779, 0.6800, 0.2429],
        [0.6655, 0.2232, 0.6216],
        [0.8547, 0.7188, 0.3372]])


Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2363, -1.1210, -0.1267],
        [ 0.6151,  0.0319,  0.6310],
        [-0.2258,  1.3509, -1.1358],
        [-1.6325,  0.0102, -0.5456],
        [-0.8484, -0.0041, -1.3924]])


Get its size:



In [0]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0110, -0.6698,  0.1776],
        [ 1.4551,  0.1268,  1.4500],
        [-0.0433,  1.8240, -1.0800],
        [-1.5115,  0.9232,  0.1556],
        [-0.6452,  0.5745, -1.0340]])


Addition: syntax 2



In [0]:
print(torch.add(x, y))

tensor([[-0.0110, -0.6698,  0.1776],
        [ 1.4551,  0.1268,  1.4500],
        [-0.0433,  1.8240, -1.0800],
        [-1.5115,  0.9232,  0.1556],
        [-0.6452,  0.5745, -1.0340]])


Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0110, -0.6698,  0.1776],
        [ 1.4551,  0.1268,  1.4500],
        [-0.0433,  1.8240, -1.0800],
        [-1.5115,  0.9232,  0.1556],
        [-0.6452,  0.5745, -1.0340]])


Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.0110, -0.6698,  0.1776],
        [ 1.4551,  0.1268,  1.4500],
        [-0.0433,  1.8240, -1.0800],
        [-1.5115,  0.9232,  0.1556],
        [-0.6452,  0.5745, -1.0340]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print(x)
print(x[:, 1])

tensor([[-0.2363, -1.1210, -0.1267],
        [ 0.6151,  0.0319,  0.6310],
        [-0.2258,  1.3509, -1.1358],
        [-1.6325,  0.0102, -0.5456],
        [-0.8484, -0.0041, -1.3924]])
tensor([-1.1210,  0.0319,  1.3509,  0.0102, -0.0041])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6556])
-0.6556460857391357


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!